In [25]:
import numpy as np
import pandas as pd

In [26]:
data = pd.read_csv('data.txt',sep=' ')
data

    年龄 有工作 有房子   信用   类别
0   青年   否   否   一般  不同意
1   青年   否   否    好  不同意
2   青年   是   否    好   同意
3   青年   是   是   一般   同意
4   青年   否   否   一般  不同意
5   中年   否   否   一般  不同意
6   中年   否   否    好  不同意
7   中年   是   是    好   同意
8   中年   否   是  非常好   同意
9   中年   否   是  非常好   同意
10  老年   否   是  非常好   同意
11  老年   否   是    好   同意
12  老年   是   否    好   同意
13  老年   是   否  非常好   同意
14  老年   否   否   一般  不同意

In [27]:
def H(p):   #计算经验熵
    p = np.array(p)
    p = p[p != 0]
    p = p / np.sum(p)
    return np.sum(-p*np.log2(p))

In [29]:
def H_D_A(data,A): #经验条件熵
    a = []
    for i in data[A]:
        if i not in a:
            a.append(i)
    print(A)
    sum = 0
    for i in a:
        p = []
        data_i = data[data[A]==i]
        p.append(len(data_i[data_i['类别']=='同意']))
        p.append(len(data_i[data_i['类别']=='不同意']))
        sum += H(p)*(len(data_i)/len(data))
    return sum

In [31]:
def g(data,A):  #信息增益
    a = []
    for i in data['类别']:
        if i not in a:
            a.append(i)
    p = []
    for i in a:
        p.append(len(data[data['类别']==i]))
    return H(p) - H_D_A(data,A)

def gr(data,A): #信息增益比
    a = []
    for i in data[A]:
        if i not in a:
            a.append(i)
    p = []
    for i in a:
        p.append(len(data[data[A]==i]))
    return g(data,A)/H(p)

In [32]:
print(g(data,'年龄'))
print(g(data,'有工作'))
print(g(data,'有房子'))
print(g(data,'信用'))

年龄
0.08300749985576883
有工作
0.32365019815155627
有房子
0.4199730940219749
信用
0.36298956253708536

In [33]:
print(gr(data,'年龄'))
print(gr(data,'有工作'))
print(gr(data,'有房子'))
print(gr(data,'信用'))

年龄
0.05237190142858302
有工作
0.3524465495205019
有房子
0.4325380677663126
信用
0.23185388128724224

In [34]:
data1 = data[data['有房子']=='是']
data1

    年龄 有工作 有房子   信用  类别
3   青年   是   是   一般  同意
7   中年   是   是    好  同意
8   中年   否   是  非常好  同意
9   中年   否   是  非常好  同意
10  老年   否   是  非常好  同意
11  老年   否   是    好  同意

In [35]:
data2 = data[data['有房子']=='否']
data2

    年龄 有工作 有房子   信用   类别
0   青年   否   否   一般  不同意
1   青年   否   否    好  不同意
2   青年   是   否    好   同意
4   青年   否   否   一般  不同意
5   中年   否   否   一般  不同意
6   中年   否   否    好  不同意
12  老年   是   否    好   同意
13  老年   是   否  非常好   同意
14  老年   否   否   一般  不同意

In [49]:
print(g(data2,'年龄'))
print(g(data2,'有工作'))
print(g(data2,'信用'))

年龄
0.2516291673878229
有工作
0.9182958340544896
信用
0.47385138961004514

In [37]:
print(gr(data2,'年龄'))
print(gr(data2,'有工作'))
print(gr(data2,'信用'))

年龄
0.1644105252727686
有工作
1.0
信用
0.34037448163185724

In [38]:
data2[data2['有工作']=='是']

    年龄 有工作 有房子   信用  类别
2   青年   是   否    好  同意
12  老年   是   否    好  同意
13  老年   是   否  非常好  同意

In [39]:
data2[data2['有工作']=='否']

    年龄 有工作 有房子  信用   类别
0   青年   否   否  一般  不同意
1   青年   否   否   好  不同意
4   青年   否   否  一般  不同意
5   中年   否   否  一般  不同意
6   中年   否   否   好  不同意
14  老年   否   否  一般  不同意